# Generated by Django 2.0.2 on 2018-02-12 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DurationField(null=True)),
                ('remarks', models.CharField(max_length=30, null=True)),
                ('score', models.FloatField(null=True)),
                ('assignment_submission_path', models.FileField(null=True, upload_to='solution_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('assignment_file_path', models.FileField(null=True, upload_to='tasks_uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('expertise', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('document', models.FileField(null=True, upload_to='tasks_uploads/')),
                ('duration', models.DurationField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='trainee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Trainee'),
        ),
        migrations.AddField(
            model_name='task',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Trainer'),
        ),
        migrations.AddField(
            model_name='task',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Training'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Task'),
        ),
        migrations.AddField(
            model_name='assignedtraining',
            name='trainee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Trainee'),
        ),
        migrations.AddField(
            model_name='assignedtraining',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Trainer'),
        ),
        migrations.AddField(
            model_name='assignedtraining',
            name='training_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingportal.Training'),
        ),
    ]
