# Generated by Django 2.0.2 on 2018-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignment_file_path',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_file_path',
            field=models.FileField(null=True, upload_to='tasks_uploads/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
