# Generated by Django 2.0.2 on 2018-02-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingportal', '0002_auto_20180221_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
